version: '3.8'
services:
  app:
    container_name: backend-container
    restart: always
    build: ./server
    ports:
      - "3500:3500"
    env_file:
      - ./server/.env
    
  client:
    container_name: frontend-container
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - app
  

